@endpoint = https://c0mog860j3.execute-api.us-east-2.amazonaws.com/prod

@token = the jwToken
GET {{endpoint}}/hello/
Authorization: {{token}}
###


GET {{endpoint}}/spaces/
###
GET {{endpoint}}/spaces?location=Nazareth

###
PUT  {{endpoint}}/spaces?location=Nazareth
Content-Type: application/json

{
    "location": "beer sheva",
    "name": "best location"
}
###
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Nazareth",
    "name": "best location"
}
###
